---
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    ports:
      - 32400:32400
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /var/lib/plexmediaserver/library:/config
      - /var/lib/plexmediaserver/plexmedia/tvshows:/tv
      - /var/lib/plexmediaserver/plexmedia/movies:/movies
    networks:
      homelab:
        external: true
    restart: unless-stopped

