
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      pihole_network:
        ipv4_address: '192.168.178.88'
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    environment:
      TZ: 'Europe/Dublin' # update according to your timezone
      WEBPASSWORD: 'pihole' #update password
    volumes:
      - '/home/garbhan/homelab/pihole/etc-pihole:/etc/pihole' #update
      - '/home/garbhnan/homelab/pihole/etc-dnsmasq.d:/etc/dnsmasq.d' #update
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

networks:
  pihole_network:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1

