---
services:
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Dublin/Europe
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /home/garbhan/homelab/deluge/config:/config
      - /var/lib/plexmediaserver/plexmedia/movies:/downloads
      - /var/lib/plexmediaserver/plexmedia/tvshows:/tvshows
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    networks:
      - homelab

networks:
  homelab:
    external: true

