---
services:

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8112 # deluge web interface
      - 58846:58846 # deluge RPC
    volumes:
      - ./gluetun:/gluetun
    env_file:
      - .env
    restart: unless-stopped

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Dublin/Europe
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /home/garbhan/homelab/deluge/config:/config
      - /var/lib/plexmediaserver/plexmedia/movies:/downloads
      - /var/lib/plexmediaserver/plexmedia/tvshows:/tvshows
    network_mode: service:gluetun

