---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

- apps:
  - memos:
      href: http://192.168.178.77:5230/
      description: nooooootes
      server: homelab
      container: memos

- monitoring:
    - grafana:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/grafana.svg
        href: http://192.168.178.77:3000/
        description: pi metrics
        server: homelab
        container: memos
    - prometheus:
        href: http://192.168.178.77:9090
        description: collects the metrics
        server: homelab
        container: memos

- misc:
  - pihole:
      href: http://192.168.178.88/admin
      description: router adblock
      server: homelab
      container: memos

